#!/bin/bash

DOCKER_CONTAINER="in_ros"

if ! docker ps --format "{{.Names}}" | grep in_ros; then
    echo "Container is not running, please launch_ros"
    exit 1
fi

if [ $# -lt 1 ]; then
    docker exec -it -u "$(id -u $USER):$(id -g $USER)" -w "$PWD" "$DOCKER_CONTAINER" bash
else
    docker exec -it -u "$(id -u $USER):$(id -g $USER)" -w "$PWD" "$DOCKER_CONTAINER" $*
fi
