on:
  push:
    tags:
      - "*"

jobs:
  create_release:
    name: Create Release for Tag
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Create Archive
        run: |
          tar -cJf in_ros-${{ github.ref_name }}.tar.xz Dockerfile in_ros launch_ros

      - name: Create Release
        uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: in_ros-${{ github.ref_name }}.tar.xz
          name: ${{ github.ref_name }}
